apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vcvigsilh-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:898d29a46c9e32a3b2f82ca65b8a7af293ae01fb@sha256:57a5fe9f9eaf259911deda0d6c3ee8c8a7a7a4ee2ce476f467530d14cad7f31d
          name: container-image
